export const technologies = [
  { name: 'Angular', djinniKeyword: 'Angular' },
  { name: 'React.js', djinniKeyword: 'React.js' },
  { name: 'Svelte', djinniKeyword: 'Svelte' },
  { name: 'Vue.js', djinniKeyword: 'Vue.js' },
  { name: 'Java', djinniKeyword: 'Java' },
  { name: 'C# / .NET', djinniKeyword: '.NET' },
  { name: 'Python', djinniKeyword: 'Python' },
  { name: 'WordPress', djinniKeyword: 'WordPress' },
  { name: 'Yii', djinniKeyword: 'Yii' },
  { name: 'Drupal', djinniKeyword: 'Drupal' },
  { name: 'Laravel', djinniKeyword: 'Laravel' },
  { name: 'Magento', djinniKeyword: 'Magento' },
  { name: 'Symfony', djinniKeyword: 'Symfony' },
  { name: 'Node.js', djinniKeyword: 'Node.js' },
  { name: 'iOS', djinniKeyword: 'iOS' },
  { name: 'Android', djinniKeyword: 'Android' },
  { name: 'React Native', djinniKeyword: 'React%20Native' },
  { name: 'C', djinniKeyword: 'C%20Lang' },
  { name: 'Embedded', djinniKeyword: 'Embedded' },
  { name: 'C++', djinniKeyword: 'CPP' },
  { name: 'Flutter', djinniKeyword: 'Flutter' },
  { name: 'Golang', djinniKeyword: 'Golang' },
  { name: 'Ruby', djinniKeyword: 'Ruby' },
  { name: 'Scala', djinniKeyword: 'Scala' },
  { name: 'Salesforce', djinniKeyword: 'Salesforce' },
  { name: 'Rust', djinniKeyword: 'Rust' },
  { name: 'Elixir', djinniKeyword: 'Elixir' },
  { name: 'Kotlin', djinniKeyword: 'Kotlin' },
  { name: 'MS Dynamics / Business Central', djinniKeyword: 'MS%20Dynamics' },
  { name: 'Odoo', djinniKeyword: 'Odoo' },
  { name: 'SAP', djinniKeyword: 'SAP' },
]
